### ISSUE TITLE
Update templated GitHub Actions to perform signing of the final policy using Sigstore

### ISSUE THREAD

**Issue by flavio** [kubewarden/swift-policy-template#1]
The GitHub actions provided by this repository should be extended to implement the signing of the wasm policy binary artifact.

## Acceptance criteria

* The wasm binary is signed using Sigstore, via the `cosign` cli
* The signature is performed using keyless signing

**Comment by jvanz** [comment]
I've removed myself from the bug to work in bug that I found in the `kubewarden-controller`

**Comment by flavio** [comment]
No worries, my plan is to find how - generally speaking - we have to change our GH action to perform signature. Once this is clear we can propagate that change everywhere.

For example, I noticed I needed to update kwctl to allow a more secure signature process. See https://github.com/kubewarden/kwctl/pull/106
